steps:
- name :  google/dart
  args : ['pub', 'get']
- name :  google/dart
  args : ['pub', 'run', 'test']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t=gcr.io/$PROJECT_ID/dart_server', '.']

images: ["gcr.io/$PROJECT_ID/dart_server"]