steps:
- name :  google/dart
  args : ['pub', 'get']
- name :  google/dart
  args : ['pub', 'run', 'test']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t=gcr.io/$PROJECT_ID/dart_server', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'dart-server'
  - '--image'
  - 'gcr.io/$PROJECT_ID/dart_server'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

images: ["gcr.io/$PROJECT_ID/dart_server"]